/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminAdminHeader: typeof import('./components/admin/AdminHeader.vue')['default']
    AdminAdminLayout: typeof import('./components/admin/AdminLayout.vue')['default']
    AdminAdminMemberUserInfo: typeof import('./components/admin/AdminMemberUserInfo.vue')['default']
    AdminAdminModal: typeof import('./components/admin/AdminModal.vue')['default']
    AdminAdminSider: typeof import('./components/admin/AdminSider.vue')['default']
    AdminBank: typeof import('./components/admin/Bank.vue')['default']
    AdminFormBulletinBoardForm: typeof import('./components/admin/form/BulletinBoardForm.vue')['default']
    AdminFormMemberGroupForm: typeof import('./components/admin/form/MemberGroupForm.vue')['default']
    AdminHeader: typeof import('./components/admin/Header.vue')['default']
    AdminHeaderWithSider: typeof import('./components/admin/HeaderWithSider.vue')['default']
    AdminLayout: typeof import('./components/admin/Layout.vue')['default']
    AdminMemberUserInfo: typeof import('./components/admin/MemberUserInfo.vue')['default']
    AdminModal: typeof import('./components/admin/Modal.vue')['default']
    AdminSearchForm: typeof import('./components/admin/SearchForm.vue')['default']
    AdminSider: typeof import('./components/admin/Sider.vue')['default']
    AdminSiderList: typeof import('./components/admin/SiderList.vue')['default']
    AdminUserInfo: typeof import('./components/admin/UserInfo.vue')['default']
    AnnouncementContent: typeof import('./components/user/AnnouncementContent.vue')['default']
    CustomButton: typeof import('./components/CustomButton.vue')['default']
    Header: typeof import('./components/user/Header.vue')['default']
    Layout: typeof import('./components/user/Layout.vue')['default']
    MobileMenu: typeof import('./components/user/MobileMenu.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MyInput: typeof import('./components/MyInput.vue')['default']
    Product: typeof import('./components/user/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/admin/SearchForm.vue')['default']
    SearchInput: typeof import('./components/user/SearchInput.vue')['default']
    UserAnnouncementContent: typeof import('./components/user/AnnouncementContent.vue')['default']
    UserHeader: typeof import('./components/user/Header.vue')['default']
    UserLayout: typeof import('./components/user/Layout.vue')['default']
    UserMarquee: typeof import('./components/user/Marquee.vue')['default']
    UserMobileMenu: typeof import('./components/user/MobileMenu.vue')['default']
    UserProduct: typeof import('./components/user/Product.vue')['default']
    UserSearchInput: typeof import('./components/user/SearchInput.vue')['default']
  }
}
