/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminBank: typeof import('./components/admin/Bank.vue')['default']
    AdminFormAnnouncementForm: typeof import('./components/admin/form/AnnouncementForm.vue')['default']
    AdminFormCreateMemberForm: typeof import('./components/admin/form/CreateMemberForm.vue')['default']
    AdminFormCreateProductForm: typeof import('./components/admin/form/CreateProductForm.vue')['default']
    AdminFormMainPointManipulateForm: typeof import('./components/admin/form/MainPointManipulateForm.vue')['default']
    AdminFormMemberGroupForm: typeof import('./components/admin/form/MemberGroupForm.vue')['default']
    AdminHeader: typeof import('./components/admin/Header.vue')['default']
    AdminHeaderWithSider: typeof import('./components/admin/HeaderWithSider.vue')['default']
    AdminLayout: typeof import('./components/admin/Layout.vue')['default']
    AdminLogInRecord: typeof import('./components/admin/LogInRecord.vue')['default']
    AdminModal: typeof import('./components/admin/Modal.vue')['default']
    AdminPointRecord: typeof import('./components/admin/PointRecord.vue')['default']
    AdminSearchForm: typeof import('./components/admin/SearchForm.vue')['default']
    AdminSider: typeof import('./components/admin/Sider.vue')['default']
    AdminSiderList: typeof import('./components/admin/SiderList.vue')['default']
    AdminUserInfo: typeof import('./components/admin/UserInfo.vue')['default']
    CustomButton: typeof import('./components/CustomButton.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAnnouncementContent: typeof import('./components/user/AnnouncementContent.vue')['default']
    UserHeader: typeof import('./components/user/Header.vue')['default']
    UserLayout: typeof import('./components/user/Layout.vue')['default']
    UserMarquee: typeof import('./components/user/Marquee.vue')['default']
    UserMobileMenu: typeof import('./components/user/MobileMenu.vue')['default']
    UserProduct: typeof import('./components/user/Product.vue')['default']
    UserSearchInput: typeof import('./components/user/SearchInput.vue')['default']
  }
}
